import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { getServerSession } from "next-auth";
import { authOptions } from "../../auth/[...nextauth]/options";

export async function GET() {

    const session = await getServerSession(authOptions);
    if (!session || !session.user) {
        return NextResponse.json({
            success: false,
            message: "unAuthorized",
        }, { status: 401 });
    }
    try {
        const user = await prisma.user.findUnique({
            where: {
                id: session.user.id,
                role: "admin"
            }
        })

        if (!user) {
            return NextResponse.json({
                success: false,
                message: "User not found",
            }, { status: 404 });
        }

        const rating = await prisma.course.findMany({
            where: {
                instructorId: user.id
            },
            select: {
                Review: {
                    select: {
                        rating: true
                    }
                }
            }
        })

        //average rating of all courses
        const avgRating = rating.map((course) => {
            const totalRating = course.Review.reduce((acc, curr) => acc + curr.rating, 0)
            return totalRating / course.Review.length
        })

        //total no. of users enrolled in the all courses
        const totalUsers = await prisma.purchasedCourses.groupBy({
            by: ['userId'],
            _count: {
                userId: true
            }
        })


        //total revenue generated by the user
        const revenue = await prisma.user.findFirst({
            where: {
                id: user.id
            }, select: {
                balance: true
            }
        })

        //total no. of courses
        const totalCourses = await prisma.course.count();

        const data = {
            avgRating: avgRating,
            totalUsers: totalUsers.length,
            revenue: revenue?.balance,
            totalCourses: totalCourses
        }

        return NextResponse.json({
            success: true,
            data
        }, { status: 200 });

    } catch (error: any) {
        return NextResponse.json({
            success: false,
            message: "Error while fetching balance",
            error: error.message
        }, { status: 500 });
    }
}
